export interface FeedbackSignal {
  id: string; type: string; metric: string; current: number | string; previous: number | string;
  delta: number | string; is_significant: boolean; action_required: boolean; diagnosis: string;
  affected_agents: string[]; adjustment: { agent: string; parameter: string; current_value: string; new_value: string; reason: string };
}

export const mockChannels = [
  { id: "ch_01", name: "FitMastery", handle: "@fitmastery", niche: "fitness", emoji: "💪", status: "active", followers: 452000, avg_engagement_rate: 6.8, target_reels_per_day: 4, viral_probability_score: 0.82, channel_health_score: 87.3, growth_velocity: 8.4, momentum_score: 0.79, ai_strategy: { hook_style: "contrarian", pacing: "fast_cuts", cta_type: "save_prompt", narration_tone: "confident" }, audience_demographics: { primary_age: "25-34", gender_split: { male: 52, female: 48 }, top_regions: ["US", "UK", "Canada"] }, best_posting_times: ["6:00 AM", "12:30 PM", "7:00 PM"] },
  { id: "ch_02", name: "TechVault", handle: "@techvault", niche: "tech", emoji: "⚡", status: "active", followers: 287000, avg_engagement_rate: 5.2, target_reels_per_day: 3, viral_probability_score: 0.74, channel_health_score: 78.1, growth_velocity: 5.2, momentum_score: 0.68, ai_strategy: { hook_style: "shocking_stat", pacing: "medium", cta_type: "follow_prompt", narration_tone: "energetic" }, audience_demographics: { primary_age: "18-24", gender_split: { male: 68, female: 32 }, top_regions: ["US", "India", "UK"] }, best_posting_times: ["8:00 AM", "1:00 PM", "9:00 PM"] },
  { id: "ch_03", name: "MindsetEngine", handle: "@mindsetengine", niche: "motivation", emoji: "🧠", status: "growing", followers: 634000, avg_engagement_rate: 7.9, target_reels_per_day: 5, viral_probability_score: 0.91, channel_health_score: 92.7, growth_velocity: 12.3, momentum_score: 0.88, ai_strategy: { hook_style: "storytelling", pacing: "dramatic", cta_type: "share_prompt", narration_tone: "authoritative" }, audience_demographics: { primary_age: "25-34", gender_split: { male: 45, female: 55 }, top_regions: ["US", "UK", "Australia"] }, best_posting_times: ["5:30 AM", "12:00 PM", "8:00 PM"] },
  { id: "ch_04", name: "FoodLabDaily", handle: "@foodlabdaily", niche: "food", emoji: "🍳", status: "active", followers: 198000, avg_engagement_rate: 8.4, target_reels_per_day: 3, viral_probability_score: 0.88, channel_health_score: 85.2, growth_velocity: 9.7, momentum_score: 0.84, ai_strategy: { hook_style: "sensory", pacing: "asmr_style", cta_type: "save_prompt", narration_tone: "warm" }, audience_demographics: { primary_age: "25-34", gender_split: { male: 28, female: 72 }, top_regions: ["US", "Canada", "UK"] }, best_posting_times: ["7:00 AM", "11:30 AM", "6:00 PM"] },
  { id: "ch_05", name: "WealthArchitect", handle: "@wealtharchitect", niche: "finance", emoji: "📈", status: "active", followers: 156000, avg_engagement_rate: 4.8, target_reels_per_day: 3, viral_probability_score: 0.65, channel_health_score: 72.4, growth_velocity: 3.1, momentum_score: 0.59, ai_strategy: { hook_style: "fear_of_missing", pacing: "medium", cta_type: "follow_prompt", narration_tone: "professional" }, audience_demographics: { primary_age: "35-44", gender_split: { male: 62, female: 38 }, top_regions: ["US", "UK", "Canada"] }, best_posting_times: ["7:00 AM", "12:00 PM", "8:30 PM"] },
  { id: "ch_06", name: "GymSecrets", handle: "@gymsecrets", niche: "fitness", emoji: "🏋️", status: "active", followers: 892000, avg_engagement_rate: 5.9, target_reels_per_day: 3, viral_probability_score: 0.77, channel_health_score: 81.6, growth_velocity: 6.8, momentum_score: 0.73, ai_strategy: { hook_style: "contrarian", pacing: "fast_cuts", cta_type: "save_prompt", narration_tone: "intense" }, audience_demographics: { primary_age: "18-24", gender_split: { male: 58, female: 42 }, top_regions: ["US", "UK", "Australia"] }, best_posting_times: ["6:00 AM", "12:30 PM", "7:00 PM"] },
  { id: "ch_07", name: "AI_Toolbox", handle: "@ai_toolbox", niche: "tech", emoji: "🤖", status: "growing", followers: 42000, avg_engagement_rate: 9.1, target_reels_per_day: 5, viral_probability_score: 0.93, channel_health_score: 94.2, growth_velocity: 14.7, momentum_score: 0.91, ai_strategy: { hook_style: "contrarian", pacing: "fast_cuts", cta_type: "follow_prompt", narration_tone: "enthusiastic" }, audience_demographics: { primary_age: "25-34", gender_split: { male: 71, female: 29 }, top_regions: ["US", "India", "Germany"] }, best_posting_times: ["8:00 AM", "1:00 PM", "9:00 PM"] },
  { id: "ch_08", name: "RiseAndGrind", handle: "@riseandgrind", niche: "motivation", emoji: "🔥", status: "active", followers: 321000, avg_engagement_rate: 6.3, target_reels_per_day: 4, viral_probability_score: 0.72, channel_health_score: 76.8, growth_velocity: 4.5, momentum_score: 0.67, ai_strategy: { hook_style: "challenge", pacing: "dramatic", cta_type: "share_prompt", narration_tone: "intense" }, audience_demographics: { primary_age: "18-24", gender_split: { male: 55, female: 45 }, top_regions: ["US", "UK", "Nigeria"] }, best_posting_times: ["5:30 AM", "12:00 PM", "8:00 PM"] },
  { id: "ch_09", name: "QuickBites", handle: "@quickbites", niche: "food", emoji: "🥘", status: "active", followers: 567000, avg_engagement_rate: 7.2, target_reels_per_day: 3, viral_probability_score: 0.79, channel_health_score: 83.4, growth_velocity: 7.2, momentum_score: 0.76, ai_strategy: { hook_style: "curiosity_gap", pacing: "asmr_style", cta_type: "save_prompt", narration_tone: "casual" }, audience_demographics: { primary_age: "25-34", gender_split: { male: 32, female: 68 }, top_regions: ["US", "Canada", "UK"] }, best_posting_times: ["7:00 AM", "11:30 AM", "6:00 PM"] },
  { id: "ch_10", name: "MoneyMinds", handle: "@moneyminds", niche: "finance", emoji: "💰", status: "active", followers: 234000, avg_engagement_rate: 5.5, target_reels_per_day: 2, viral_probability_score: 0.68, channel_health_score: 75.3, growth_velocity: 4.2, momentum_score: 0.63, ai_strategy: { hook_style: "shocking_stat", pacing: "medium", cta_type: "save_prompt", narration_tone: "calm" }, audience_demographics: { primary_age: "35-44", gender_split: { male: 57, female: 43 }, top_regions: ["US", "UK", "Singapore"] }, best_posting_times: ["7:00 AM", "12:00 PM", "8:30 PM"] },
  { id: "ch_11", name: "DailyAesthetic", handle: "@dailyaesthetic", niche: "lifestyle", emoji: "✨", status: "active", followers: 178000, avg_engagement_rate: 6.1, target_reels_per_day: 3, viral_probability_score: 0.71, channel_health_score: 79.8, growth_velocity: 5.9, momentum_score: 0.72, ai_strategy: { hook_style: "relatable", pacing: "smooth", cta_type: "follow_prompt", narration_tone: "warm" }, audience_demographics: { primary_age: "18-24", gender_split: { male: 22, female: 78 }, top_regions: ["US", "UK", "Australia"] }, best_posting_times: ["9:00 AM", "2:00 PM", "8:00 PM"] },
  { id: "ch_12", name: "HomeFitPro", handle: "@homefitpro", niche: "fitness", emoji: "🏃", status: "active", followers: 95000, avg_engagement_rate: 7.8, target_reels_per_day: 3, viral_probability_score: 0.84, channel_health_score: 88.9, growth_velocity: 10.3, momentum_score: 0.82, ai_strategy: { hook_style: "challenge", pacing: "fast_cuts", cta_type: "save_prompt", narration_tone: "encouraging" }, audience_demographics: { primary_age: "25-34", gender_split: { male: 38, female: 62 }, top_regions: ["US", "UK", "Canada"] }, best_posting_times: ["6:00 AM", "12:30 PM", "7:00 PM"] },
]

export const mockTrends = [
  { id: "tr_01", name: "AI Voice Cloning Demos", niche: "tech", source: "tiktok", type: "format", confidence: 0.92, saturation: 0.48, opportunity: 0.84, velocity: 0.89, growth_24h: 34.2, growth_7d: 127.5, status: "rising", viral_hooks: ["This AI clones your voice in 3 seconds", "I cloned myself with AI", "Stop using your real voice"], emotional_patterns: ["curiosity", "fear", "surprise"] },
  { id: "tr_02", name: "Silent Workout Routines", niche: "fitness", source: "instagram", type: "sensory", confidence: 0.88, saturation: 0.55, opportunity: 0.78, velocity: 0.82, growth_24h: 18.7, growth_7d: 89.3, status: "hot", viral_hooks: ["No talking just lifting", "ASMR gym sounds", "Quiet workout that hits different"], emotional_patterns: ["satisfaction", "aspiration", "focus"] },
  { id: "tr_03", name: "30-Second Recipe Hacks", niche: "food", source: "tiktok", type: "format", confidence: 0.95, saturation: 0.42, opportunity: 0.87, velocity: 0.93, growth_24h: 42.1, growth_7d: 156.8, status: "viral", viral_hooks: ["1 minute meal that changed my life", "Stop overcooking your pasta", "This 30-second hack is illegal"], emotional_patterns: ["convenience", "surprise", "satisfaction"] },
  { id: "tr_04", name: "Stoic Morning Routines", niche: "motivation", source: "youtube", type: "theme", confidence: 0.86, saturation: 0.51, opportunity: 0.76, velocity: 0.74, growth_24h: 12.3, growth_7d: 67.2, status: "rising", viral_hooks: ["Marcus Aurelius starts his day like this", "The Stoic morning routine", "This 2000-year-old routine still works"], emotional_patterns: ["discipline", "aspiration", "reverence"] },
  { id: "tr_05", name: "Passive Income Breakdowns", niche: "finance", source: "twitter", type: "educational", confidence: 0.83, saturation: 0.63, opportunity: 0.69, velocity: 0.68, growth_24h: 8.9, growth_7d: 45.1, status: "stable", viral_hooks: ["$0 to $10K/month with this method", "Passive income they don't teach in school", "I make money while sleeping — here's how"], emotional_patterns: ["aspiration", "fear_of_missing", "curiosity"] },
  { id: "tr_06", name: "POV Coding Challenges", niche: "tech", source: "tiktok", type: "format", confidence: 0.79, saturation: 0.33, opportunity: 0.91, velocity: 0.72, growth_24h: 56.7, growth_7d: 203.4, status: "emerging", viral_hooks: ["POV: you're speed coding an app", "Building a full stack in 60 seconds", "Watch me code this from scratch"], emotional_patterns: ["impressive", "curiosity", "aspiration"] },
  { id: "tr_07", name: "Micro-Habit Stacking", niche: "motivation", source: "reddit", type: "concept", confidence: 0.81, saturation: 0.28, opportunity: 0.92, velocity: 0.65, growth_24h: 67.3, growth_7d: 189.2, status: "emerging", viral_hooks: ["The 2-minute habit that changed my life", "Stack these 3 habits for unstoppable growth", "Atomic Habits lied to you — here's the real method"], emotional_patterns: ["curiosity", "self_improvement", "hope"] },
  { id: "tr_08", name: "Before/After Transformations", niche: "fitness", source: "instagram", type: "visual", confidence: 0.94, saturation: 0.61, opportunity: 0.73, velocity: 0.87, growth_24h: 28.4, growth_7d: 98.6, status: "hot", viral_hooks: ["Wait for the transformation", "Day 1 vs Day 365", "The difference 90 days makes"], emotional_patterns: ["aspiration", "surprise", "social_proof"] },
]

export const mockAgents = [
  { type: "trend_hunter", description: "Scans platforms for emerging trends, viral hooks, and rising formats", dependencies: [], outputs: ["trends", "viral_hooks", "emerging_formats"], status: "idle", runs_today: 24, success_rate: 0.96 },
  { type: "competitor_intel", description: "Monitors competitor channels and reverse-engineers winning patterns", dependencies: ["trend_hunter"], outputs: ["competitor_analysis", "gap_opportunities"], status: "idle", runs_today: 18, success_rate: 0.93 },
  { type: "hook_generator", description: "Generates scroll-stopping hooks using viral pattern analysis and retention data", dependencies: ["trend_hunter", "viral_analyzer", "analytics_feedback"], outputs: ["hooks", "hook_variations", "predicted_retention"], status: "idle", runs_today: 42, success_rate: 0.91 },
  { type: "script_writer", description: "Writes high-retention short-form scripts with viral pacing and emotional arcs", dependencies: ["hook_generator", "trend_hunter", "content_memory"], outputs: ["script", "pacing_notes", "cta", "emotional_arc"], status: "idle", runs_today: 36, success_rate: 0.94 },
  { type: "viral_analyzer", description: "Reverse-engineers viral content to create reusable templates", dependencies: ["trend_hunter"], outputs: ["viral_templates", "pattern_breakdown"], status: "idle", runs_today: 15, success_rate: 0.89 },
  { type: "voiceover", description: "Generates AI voiceovers with tone and emotion calibrated to the script", dependencies: ["script_writer"], outputs: ["voiceover_url", "voice_settings"], status: "idle", runs_today: 30, success_rate: 0.97 },
  { type: "scene_planner", description: "Plans visual scenes and shot compositions based on script emotional arc", dependencies: ["script_writer", "trend_hunter"], outputs: ["scene_plan", "shot_list", "storyboard"], status: "idle", runs_today: 28, success_rate: 0.95 },
  { type: "video_generator", description: "Generates AI video content assembled with FFmpeg into final reels", dependencies: ["scene_planner", "voiceover", "brand_consistency"], outputs: ["video_url", "assembly_report"], status: "idle", runs_today: 22, success_rate: 0.88 },
  { type: "thumbnail_optimizer", description: "Generates and A/B tests cover thumbnails with attention heatmaps", dependencies: ["video_generator", "brand_consistency"], outputs: ["thumbnail_variants", "predicted_ctr"], status: "idle", runs_today: 20, success_rate: 0.92 },
  { type: "caption_generator", description: "Generates SEO-optimized captions with hashtag strategies and engagement hooks", dependencies: ["script_writer", "analytics_feedback", "content_memory"], outputs: ["caption", "hashtag_strategy", "cta_text"], status: "idle", runs_today: 34, success_rate: 0.95 },
  { type: "posting_scheduler", description: "Optimizes posting schedules using audience activity and A/B tested time slots", dependencies: ["analytics_feedback", "competitor_intel"], outputs: ["schedule", "optimal_times"], status: "idle", runs_today: 12, success_rate: 0.98 },
  { type: "analytics_feedback", description: "THE CORE ENGINE — analyzes retention, watch time, and engagement to auto-adjust strategies", dependencies: [], outputs: ["feedback_signals", "strategy_adjustments", "agent_directives"], status: "idle", runs_today: 48, success_rate: 0.94 },
  { type: "content_memory", description: "Maintains niche-specific memory banks of high-performing patterns and audience psychology", dependencies: ["analytics_feedback"], outputs: ["memory_bank", "successful_patterns", "cross_channel_insights"], status: "idle", runs_today: 16, success_rate: 0.97 },
  { type: "brand_consistency", description: "Ensures all content maintains consistent brand voice and visual identity across channels", dependencies: ["content_memory", "script_writer", "scene_planner"], outputs: ["brand_check_result", "consistency_score"], status: "idle", runs_today: 25, success_rate: 0.96 },
]

export const mockFeedbackSignals: FeedbackSignal[] = [
  { id: "sig_001", type: "retention_drop", metric: "hook_retention", current: 0.42, previous: 0.58, delta: -0.16, is_significant: true, action_required: true, diagnosis: "First 2 seconds losing 16% more viewers than baseline. Hooks are weakening.", affected_agents: ["hook_generator", "scene_planner"], adjustment: { agent: "hook_generator", parameter: "hook_first_frame_duration", current_value: "2.0s", new_value: "1.0s", reason: "Shorter hook openings show 23% better retention in A/B tests" } },
  { id: "sig_002", type: "engagement_spike", metric: "share_to_view_ratio", current: 0.034, previous: 0.018, delta: 0.016, is_significant: true, action_required: true, diagnosis: "Shares doubled when using opinionated/controversial takes. Amplify this pattern.", affected_agents: ["script_writer", "hook_generator"], adjustment: { agent: "script_writer", parameter: "opinion_strength", current_value: "moderate", new_value: "strong", reason: "Opinionated scripts drive 89% more shares per 1K views" } },
  { id: "sig_003", type: "completion_improvement", metric: "completion_rate", current: 0.38, previous: 0.29, delta: 0.09, is_significant: true, action_required: true, diagnosis: "Faster cuts and shorter scenes correlate with higher completion rates.", affected_agents: ["scene_planner", "video_generator"], adjustment: { agent: "scene_planner", parameter: "avg_scene_duration", current_value: "4.5s", new_value: "3.0s", reason: "Reducing scene length from 4.5s to 3.0s improved completion by 31%" } },
  { id: "sig_004", type: "audience_shift", metric: "female_audience_pct", current: 0.62, previous: 0.48, delta: 0.14, is_significant: true, action_required: true, diagnosis: "Female audience share growing. Content resonates more with storytelling format.", affected_agents: ["script_writer", "voiceover"], adjustment: { agent: "script_writer", parameter: "narrative_style", current_value: "informational", new_value: "storytelling", reason: "Storytelling format shows 45% higher retention among female 25-34 demo" } },
  { id: "sig_005", type: "timing_optimization", metric: "best_posting_hour", current: "7:00 PM", previous: "6:00 PM", delta: "+1h", is_significant: true, action_required: true, diagnosis: "Peak engagement shifted 1 hour later. Update posting schedule.", affected_agents: ["posting_scheduler"], adjustment: { agent: "posting_scheduler", parameter: "evening_slot", current_value: "6:00 PM", new_value: "7:00 PM", reason: "Audience activity peak moved from 6PM to 7PM over last 2 weeks" } },
]

export const mockDashboardStats = {
  total_channels: 12,
  active_channels: 11,
  total_followers: 3864000,
  avg_engagement_rate: 6.6,
  avg_viral_score: 0.79,
  avg_health_score: 82.9,
  total_target_reels_daily: 41,
  niches_active: 5,
  top_performing_niche: "food",
}
